knowledge_bases:
  medline_test:
    name: "MedlinePlus Test"
    description: "MedlinePlus medical articles"

    pinecone_index_name: "PINECONE_MEDLINE_TEST_INDEX_NAME"  # References .env variable
    embedding_model: "RPRTHPB-text-embedding-3-small"
    LLM_model: "RPRTHPB-gpt-5-mini"
    embedding_dimensions: 512
    bm25_k: 20
    vector_k: 2
    bm25_weight: 0.0
    vector_weight: 1.0
    final_k: 2


# RRF Configuration
rrf:
  c: 60  # Constant for RRF formula: 1 / (rank + c)

# Embedding API Configuration
embeddings:
  base_url: "https://api.llmod.ai/v1"
  api_key_env: "OPENAI_API_KEY"

reranker:
  use_reranker: "no"
  name: "cross-encoder/ms-marco-MiniLM-L6-v2"

LLM:
  base_url: "https://api.llmod.ai/v1"
  api_key_env: "OPENAI_API_KEY"
  max_tokens: 400